export const Context = {
    prisma: 'PRISMA',
    //////////////////////
    counts: 'COUNTS',
    //////////////////////
    auth: 'AUTH',
    user: 'USER',
    users: 'USERS',
    car: 'Car',
    cars: 'Cars',
    agency: 'Agency',
    agencies: 'Agencies',
    driver: 'Driver',
    drivers: 'Drivers',
    employee: 'Employee',
    employees: 'Employees',
    complain: 'Complain',
    complains: 'Complains',
    trailer: 'Trailer',
    trailers: 'Trailers',
    request: 'Request',
    requests: 'Requests',
    profile: 'Profile',
    profiles: 'Profiles',
    address: 'Address',
    driverDocument: 'Driver Documents',
    drugTest: 'Drug Test',
    driverLicense: 'Driver License',
    visa: 'Visa',
    driverPassport: 'Driver passport',
};
